export const PictureMap: Record<string, string> = {
  "Alianza del Viejo Mundo": "/assets/images/teams/OldWorld-Alliance.webp",
  "Altos Elfos": "/assets/images/teams/High-Elf.webp",
  Amazonas: "/assets/images/teams/Amazons.webp",
  Bretonia: "/assets/images/teams/Bretonnie_Logo.webp",
  "Demonios de Khorne": "/assets/images/teams/daemons-of-khorne.webp",
  "Elegidos del Caos": "/assets/images/teams/Chaos.webp",
  "Elfos Oscuros": "/assets/images/teams/Dark-Elf.webp",
  "Elfos Silvanos": "/assets/images/teams/Wood-Elf.webp",
  Enanos: "/assets/images/teams/Dwarf.webp",
  "Enanos del Caos": "/assets/images/teams/Chaos-Dwarf.webp",
  Gnomos: "/assets/images/teams/Logo_Gnome.webp",
  Goblins: "/assets/images/teams/Goblin.webp",
  "Habitantes del Inframundo": "/assets/images/teams/Underworld.webp",
  Halflings: "/assets/images/teams/Halflings.webp",
  "Hombres Lagarto": "/assets/images/teams/Lizardmen.webp",
  Humanos: "/assets/images/teams/Human.webp",
  Khemri: "/assets/images/teams/Khemri.webp",
  Khorne: "/assets/images/teams/Khorne_banner.png.webp",
  Nigromantes: "/assets/images/teams/Necromantic.webp",
  "Nobleza Imperial": "/assets/images/teams/Imperial.webp",
  "No-Muertos": "/assets/images/teams/Undead.webp",
  Nórdicos: "/assets/images/teams/Norse.webp",
  Nurgle: "/assets/images/teams/Nurgle.webp",
  Ogros: "/assets/images/teams/Ogre.webp",
  Orcos: "/assets/images/teams/Orc.webp",
  "Orcos Negros": "/assets/images/teams/Black-Orc.webp",
  "Renegados del Caos": "/assets/images/teams/Chaos-Chosen.webp",
  Skavens: "/assets/images/teams/Skaven.webp",
  Slaanesh: "/assets/images/teams/slaanesh.webp",
  Slann: "/assets/images/teams/Slann.webp",
  Snotlings: "/assets/images/teams/Snotling.webp",
  "Unión Élfica": "/assets/images/teams/Elven-Union.webp",
  Vampiros: "/assets/images/teams/Vampire.webp",
};
