export const teams = [
  {
    name: "Alianza del Viejo Mundo",
    hidden: true,
  },
  {
    name: "Altos Elfos",
    hidden: true,
  },
  {
    name: "Amazonas",
    tier: 1,
    hidden: true,
  },
  {
    name: "Bretonia",
    hidden: true,
  },
  {
    name: "Demonios de Khorne",
    hidden: true,
  },
  {
    name: "Elegidos del Caos",
    tier: 2,
    hidden: true,
  },
  {
    name: "Elfos Oscuros",
    hidden: true,
  },
  {
    name: "Elfos Silvanos",
    tier: 1,
    players: [
      {
        name: "Línea",
        max: 12,
        min: 0,
        cost: 70,
        movement: 7,
        strength: 3,
        agility: 2,
        passing: 4,
        armor: 8,
        skills: [],
        primary: "AG",
        secondary: "F",
      },
      {
        name: "Thrower",
        max: 2,
        min: 0,
        cost: 95,
        movement: 7,
        strength: 3,
        agility: 2,
        passing: 2,
        armor: 8,
        skills: ["Pasar"],
        primary: "AGP",
        secondary: "F",
      },
      {
        name: "Catcher",
        max: 4,
        min: 0,
        cost: 90,
        movement: 8,
        strength: 2,
        agility: 2,
        passing: 4,
        armor: 8,
        skills: ["Atrapar", "Esquivar"],
        primary: "AG",
        secondary: "PF",
      },
      {
        name: "Wardancer",
        max: 2,
        min: 0,
        cost: 125,
        movement: 8,
        strength: 3,
        agility: 2,
        passing: 4,
        armor: 8,
        skills: ["Placar", "Esquivar", "Saltar"],
        primary: "AG",
        secondary: "PF",
      },
      {
        name: "Loren Forest Treeman",
        max: 1,
        min: 0,
        cost: 120,
        movement: 2,
        strength: 6,
        agility: 5,
        passing: 5,
        armor: 11,
        skills: [
          "Solitario (4+)",
          "Golpe Mortifero (+1)",
          "Mantenerse Firme",
          "Brazo Fuerte",
          "Echar Raíces",
          "Cabeza Dura",
          "Lanzar Compañero",
        ],
        primary: "F",
        secondary: "AG",
      },
      {
        name: "ReRolls",
        max: 8,
        min: 0,
        cost: 50,
      },
    ],
  },
  {
    name: "Enanos",
    hidden: true,
  },
  {
    name: "Enanos del Caos",
    tier: 1,
    players: [
      {
        name: "Hobgoblin",
        max: 16,
        min: 0,
        cost: 40,
        movement: 6,
        strength: 3,
        agility: 3,
        passing: 4,
        armor: 8,
        skills: [],
        primary: "G",
        secondary: "F",
      },
      {
        name: "Sneaky Stabba",
        max: 2,
        min: 0,
        cost: 70,
        movement: 6,
        strength: 3,
        agility: 3,
        passing: 5,
        armor: 8,
        skills: ["Perseguir", "Apuñalar"],
        primary: "G",
        secondary: "F",
      },
      {
        name: "Enano del Caos",
        max: 4,
        min: 0,
        cost: 70,
        movement: 4,
        strength: 3,
        agility: 4,
        passing: 6,
        armor: 10,
        skills: ["Placar", "Cabeza Dura", "Piel Férrea"],
        primary: "GF",
        secondary: "F",
      },
      {
        name: "FlameSmith",
        max: 2,
        min: 0,
        cost: 80,
        movement: 5,
        strength: 3,
        agility: 4,
        passing: 6,
        armor: 10,
        skills: [
          "Aliento de Fuego",
          "Cabeza Dura",
          "Luchador",
          "Presencia Perturbadora",
        ],
        primary: "GF",
        secondary: "F",
      },
      {
        name: "Bull Centaur",
        max: 2,
        min: 0,
        cost: 130,
        movement: 6,
        strength: 4,
        agility: 4,
        passing: 6,
        armor: 10,
        skills: ["Esprintar", "Pies Firmes", "Cabeza Dura"],
        primary: "GF",
        secondary: "F",
      },
      {
        name: "Minotaur",
        max: 1,
        min: 0,
        cost: 150,
        movement: 5,
        strength: 5,
        agility: 4,
        passing: "-",
        armor: 9,
        skills: [
          "Furia",
          "Cuernos",
          "Ira Descontrolada",
          "Solitario (4+)",
          "Golpe Mortífero (+1)",
          "Cabeza Dura",
        ],
        primary: "F",
        secondary: "G",
      },
      {
        name: "ReRolls",
        max: 8,
        min: 0,
        cost: 70,
      },
    ],
  },
  {
    name: "Gnomos",
    hidden: true,
  },
  {
    name: "Goblins",
    hidden: true,
  },
  {
    name: "Habitantes del Inframundo",
    hidden: true,
  },
  {
    name: "Halflings",
    hidden: true,
  },
  {
    name: "Hombres Lagarto",
    hidden: true,
  },
  {
    name: "Humanos",
    hidden: true,
  },
  {
    name: "Khemri",
    hidden: true,
  },
  {
    name: "Khorne",
    hidden: true,
  },
  {
    name: "Nigromantes",
    hidden: true,
  },
  {
    name: "Nobleza Imperial",
    tier: 2,
    players: [
      {
        name: "Retainer Lineman",
        max: 12,
        min: 0,
        cost: 45,
        movement: 6,
        strength: 3,
        agility: 4,
        passing: 4,
        armor: 8,
        skills: ["Zafarse"],
        primary: "AG",
        secondary: "F",
      },
      {
        name: "Thrower",
        max: 2,
        min: 0,
        cost: 75,
        movement: 6,
        strength: 3,
        agility: 4,
        passing: 3,
        armor: 8,
        skills: ["Pasar", "Pase En Carrera"],
        primary: "AGP",
        secondary: "F",
      },
      {
        name: "Noble Blitzer",
        max: 2,
        min: 0,
        cost: 105,
        movement: 7,
        strength: 3,
        agility: 4,
        passing: 4,
        armor: 9,
        skills: ["Placar", "Atrapar"],
        primary: "AG",
        secondary: "F",
      },
      {
        name: "Bodyguards",
        max: 4,
        min: 0,
        cost: 90,
        movement: 6,
        strength: 3,
        agility: 4,
        passing: 4,
        armor: 9,
        skills: ["Mantenerse Firme", "Forcejeo"],
        primary: "AG",
        secondary: "F",
      },
      {
        name: "Ogre",
        max: 1,
        min: 0,
        cost: 140,
        movement: 5,
        strength: 5,
        agility: 2,
        passing: 5,
        armor: 10,
        skills: ["Estúpido", "Solitario (4+)", "Golpe Mortífero (+1)"],
        primary: "F",
        secondary: "G",
      },
      {
        name: "ReRolls",
        max: 8,
        min: 0,
        cost: 70,
      },
    ],
  },
  {
    name: "No-Muertos",
    hidden: true,
  },
  {
    name: "Nórdicos",
    tier: 1,
    players: [
      {
        name: "Linemen",
        max: 16,
        min: 0,
        cost: 50,
        movement: 6,
        strength: 3,
        agility: 3,
        passing: 4,
        armor: 8,
        skills: ["Placar"],
        primary: "G",
        secondary: "F",
      },
      {
        name: "Beer Boar",
        max: 2,
        min: 0,
        cost: 20,
        movement: 5,
        strength: 4,
        agility: 3,
        passing: null,
        armor: 6,
        skills: [
          "Esquivar",
          "Sin Manos",
          "Bebida Reconstituyente",
          "Escurridizo",
          "Canijo",
        ],
        primary: "G",
        secondary: "F",
      },
      {
        name: "Berserker",
        max: 2,
        min: 0,
        cost: 90,
        movement: 6,
        strength: 3,
        agility: 3,
        passing: 5,
        armor: 8,
        skills: ["Placar", "Furia", "En Pie de un Salto"],
        primary: "GS",
        secondary: "F",
      },
      {
        name: "Valkyrie",
        max: 2,
        min: 0,
        cost: 95,
        movement: 7,
        strength: 3,
        agility: 3,
        passing: 3,
        armor: 8,
        skills: ["Atrapar", "Agallas", "Pasar", "Robar Balón"],
        primary: "AGP",
        secondary: "F",
      },
      {
        name: "Ulfwerener",
        max: 2,
        min: 0,
        cost: 105,
        movement: 6,
        strength: 4,
        passing: null,
        agility: 3,
        armor: 9,
        skills: ["Furia"],
        primary: "GS",
        secondary: "F",
      },
      {
        name: "Yhetee",
        max: 1,
        min: 0,
        cost: 140,
        movement: 5,
        strength: 5,
        agility: 4,
        passing: null,
        armor: 9,
        skills: [
          "Garras",
          "Presencia Perturbadora",
          "Furia",
          "Solitario(4+)",
          "Ira Descontrolada",
        ],
        primary: "F",
        secondary: "AG",
      },
      {
        name: "ReRolls",
        max: 8,
        min: 0,
        cost: 60,
      },
    ],
  },
  {
    name: "Nurgle",
    hidden: true,
  },
  {
    name: "Ogros",
    hidden: true,
  },
  {
    name: "Orcos",
    hidden: true,
  },
  {
    name: "Orcos Negros",
    tier: 2,
    players: [
      {
        name: "Goblin Bruiser",
        max: 12,
        min: 0,
        cost: 45,
        movement: 6,
        strength: 2,
        agility: 3,
        passing: 4,
        armor: 8,
        skills: ["Esquivar", "Humanoide Bala", "Escurridizo", "Cabeza Dura"],
        primary: "A",
        secondary: "GPS",
      },
      {
        name: "Black Orc",
        max: 6,
        min: 0,
        cost: 90,
        movement: 4,
        strength: 4,
        agility: 4,
        passing: 4,
        armor: 10,
        skills: ["Luchador", "Apartar"],
        primary: "GS",
        secondary: "AP",
      },
      {
        name: "Troll Adiestrado",
        max: 1,
        min: 0,
        cost: 115,
        movement: 4,
        strength: 5,
        agility: 5,
        passing: 5,
        armor: 10,
        skills: [
          "Siempre Hambriento",
          "Solitario (3+)",
          "Golpe Mortífero(+1)",
          "Proyectil Vómito",
          "Realmente Estúpido",
          "Regeneración",
          "Lanzar Compañero",
        ],
        primary: "S",
        secondary: "AGP",
      },
      {
        name: "ReRolls",
        max: 8,
        min: 0,
        cost: 60,
      },
    ],
  },
  {
    name: "Renegados del Caos",
    hidden: true,
  },
  {
    name: "Skavens",
    tier: 1,
    players: [
      {
        name: "Linerat",
        max: 16,
        min: 0,
        cost: 50,
        movement: 7,
        strength: 3,
        agility: 3,
        passing: 4,
        armor: 8,
        skills: [],
        primary: "G",
        secondary: "AMS",
      },
      {
        name: "Thrower",
        max: 2,
        min: 0,
        cost: 85,
        movement: 7,
        strength: 3,
        agility: 3,
        passing: 2,
        armor: 8,
        skills: ["Manos Seguras", "Pasar"],
        primary: "GP",
        secondary: "AMS",
      },
      {
        name: "Gutter Runner",
        max: 4,
        min: 0,
        cost: 85,
        movement: 9,
        strength: 2,
        agility: 2,
        passing: 4,
        armor: 8,
        skills: ["Esquivar"],
        primary: "AG",
        secondary: "MPS",
      },
      {
        name: "Blitzer",
        max: 2,
        min: 0,
        cost: 90,
        movement: 7,
        strength: 3,
        agility: 3,
        passing: 5,
        armor: 9,
        skills: ["Placar"],
        primary: "GS",
        secondary: "AMP",
      },
      {
        name: "Rat Ogre",
        max: 1,
        min: 0,
        cost: 150,
        movement: 6,
        strength: 5,
        agility: 4,
        passing: null,
        armor: 9,
        skills: [
          "Animal Feroz",
          "Cola Prensil",
          "Furia",
          "Golpe Mortifero(+1)",
          "Solitario (4+)",
        ],
        primary: "S",
        secondary: "AGM",
      },
      {
        name: "ReRolls",
        max: 8,
        min: 0,
        cost: 50,
      },
    ],
  },
  {
    name: "Slaanesh",
    hidden: true,
  },
  {
    name: "Slann",
    hidden: true,
  },
  {
    name: "Snotlings",
    hidden: true,
  },
  {
    name: "Unión Élfica",
    hidden: true,
  },
  {
    name: "Vampiros",
    hidden: true,
  },
];
